job update

diff --git a/.github/workflows/golangci-lint.yml b/.github/workflows/golangci-lint.yml
--- a/.github/workflows/golangci-lint.yml
+++ b/.github/workflows/golangci-lint.yml
@@ -11,17 +11,27 @@ permissions:
 
 jobs:
   golangci:
+    name: Lint All Services
     runs-on: ubuntu-latest
     steps:
-      - name: Setup Go
-        uses: actions/setup-go@v4
+      - uses: actions/checkout@v4
+      - uses: actions/setup-go@v5
         with:
-          go-version: 1.22.3
-      - name: Checkout code
-        uses: actions/checkout@v3
+          go-version: stable
 
-      - name: Install golangci-lint
+      - name: Setup golangci-lint
+        uses: golangci/golangci-lint-action@v6
+        with:
+          version: v1.60
+
+      - name: Lint all services
         run: |
-          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.54.2
-      - name: Run linter
-        run: ./lint_all_services.sh
+          if [ ! -f .golangci.yml ]; then
+            echo "Configuration file .golangci.yml not found in the root directory."
+            exit 1
+          fi
+
+          for dir in $(find . -name "go.mod" -exec dirname {} \;); do
+            echo "Running golangci-lint in $dir"
+            (cd "$dir" && golangci-lint run -c ../.golangci.yml)
+          done
